dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - if [[ $TRAVIS_PYTHON_VERSION == "3.8" ]]; then
        pipenv run coverage run --source=./ setup.py test;
    else
        pipenv run python setup.py test;
    fi

after_success:
  # Bash uploader fails when coverage is uploaded conditionally.
  # See: https://github.com/codecov/codecov-bash/issues/133
  - if [[ $TRAVIS_PYTHON_VERSION == "3.8" ]]; then
        pip install codecov && codecov;
    fi

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "QwGF6o/YzgNYtjab5S2KXnOEuDWET6sHgqHGK0GZDpptXsdDWY9fjP+OKjuBGNt3Mj3QDNjL8gtkgDjhTzOHIxu8n9RQkWlKrC3k7MByxmD7T20HEeE+stAFTLhUbIb6FoEhu1O+AssBbxNQovuh/jNiwRoDsbQx1X9Yi+goBpal6pIKHoP3yZW8zRH272WUn0pblI4uoZ0Z/YuU27LAVZeEadpEj8+Z9kZzsax4kPzF/nooE50Z3UwBxU/gIsdxX3O3MMXaj1P2g8pbbogm8puWX/nfC6ohg5IEdTGuBvBgvku2TkjCLVXzSXOHAX7ZCD+WRJS+Y0nG4pp7AoxijfiFffGCpTyKcFKznP5NyebswrzBXfY3M/LnANgm8gaJKeDf0D8r2REMUa7qhsTrncBzZpmhDiZLDQ1sBV6nZY5gL036gaT4zmKAEWjC9NRhbDOh45r8D455gnr8b2jKzPMCtZK5ELDVDinegKaCbjZr7Q/RCw3SSUV9qpKuR+K33FJ2t9AJJafHdsyfMj+BlYCCqq1f7o4PIPueqpqWuqudw4cUTeEM/9RcyHDgOduZvlGEuowHLUdwoyfRVMX/5wFS7/PrW3Fj+PtS6nY3Zd70fpV2453RCg56HxNf/wRoiu/R87HjrDe7k2t8hWSBaYyVa753u8fCPA2MunCTgPc="
  skip_existing: true
  on:
    tags: true
