dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - if [[ $TRAVIS_PYTHON_VERSION == "3.8" ]]; then
        pipenv run coverage run --source=./ setup.py test;
    else
        pipenv run python setup.py test;
    fi

after_success:
  # Bash uploader fails when coverage is uploaded conditionally.
  # See: https://github.com/codecov/codecov-bash/issues/133
  - if [[ $TRAVIS_PYTHON_VERSION == "3.8" ]]; then
        pip install codecov && codecov;
    fi

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "bcD2763aiE0lGBSspztrHqo5w52J4WwDszrN+x/yMm2GVRiZ1cJkvP64Xghrof221EYcB2yovMUAo7iWsdvrk5XQcOed7weyF9ruQtqjWAupBRt3RBPt3nFWZCMt6l8gT5p/8iSpijGi5DQLbMGvdZNviiFNwEk0uQYrKAwJ/1IItcHfddgIRy6ToJyEew7aMpSVQeonra2HPKvh9lq7q7pwI/Fbu9AEF335eVDVqdkUXj4OmsQaFvBOzw40l1T8SN5Mr1Oq7kyg499+IdOXyeQMSfsNoFXLygcim6GOpe/wVH/DycCoDDoQbGPYadua3/r3R0OFVTkKixm0R/5VlOiJbC3xStzYNA+RCOwJdwCKwWUMZt78+ULCG+bwl1NQQ1gZcgK6CmbDk+v91D3+2UfmLEYm0yFlPacJmVtC68qmlO+3WTqX+O7r9mQw078al9xUs1MQK3Q5CMckDDTsdKxhm5Uat0UqiPfHzkcr9fluZzdTc7PXqXNS23tH/4ujyR3QiCoZjQtKk80nOxhkssgN0B/gu/xN1gGuvd++v1ueMW7ko86H+phvsM/TUjT73KBqVGT2GVqbPl0kfyry477yvask4/Bi1wlJC2XMIntartcyD6/89OsLzTKPkBbBM+Ronjn+CQzmjBUttP7SGHnyOftaSXWuZEwiFjJNF/s="
  skip_existing: true
  on:
    tags: true
